# Generated by Django 4.0.5 on 2022-06-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=b'I00\n', max_length=100)),
                ('food_pic', models.ImageField(upload_to='photos')),
                ('category', models.CharField(choices=[('Meal', 'Meal'), ('Fast Food', 'Fast Food'), ('Drink', 'Drink'), ('Other', 'Other')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('user_name', models.CharField(blank=b'I00\n', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=200)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
